name: release-pr

on:
  push:
    branches:
      - develop

jobs:
  release-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get current timestamp
        id: timestamp
        run: echo "now=$(TZ='Asia/Tokyo' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Create Release PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if there's already an open PR from develop to main with the 'release' label
          existing_pr=$(gh pr list --state open --head develop --base main --label release --json number --jq '.[0].number')
          if [[ "$existing_pr" != 'null' ]] && [[ -n "$existing_pr" ]]; then
            echo "Release PR already exists: #$existing_pr"
            echo 'Updating existing PR title...'
            gh pr edit $existing_pr --title "Release ${{ steps.timestamp.outputs.now }}"
          else
            echo 'Creating new Release PR...'
            pr_url=$(gh pr create --title "Release ${{ steps.timestamp.outputs.now }}" --body '🤖 This release PR was automatically generated by https://github.com/himura467/tend-attend-be/blob/462475d17bf07d53aa031ab229305af433c18ba4/.github/workflows/release-pr.yml' --head develop --base main)
            pr_number=$(gh pr view "$pr_url" --json number --jq '.number')
            gh pr edit "$pr_number" --add-label 'release'
          fi
